keyevents:
  BACK: 4 #后退
  HOME: 3 #(HOME)
  UP: 19 #（向上按键）
  DOWN: 20 #（向下按键）
  LEFT: 21 #（向左按键）
  RIGHT: 22 #（向右按键）
  OK: 23 #（ok按键）
  VOLUP: 24 #（声音放大）
  VOLDOWN: 25 #（声音放小）
  POWER: 26 #电源
  ENTER: 6 #输入确认
  DEL: 67 #输入删除
  A: 29
  B: 30
  C: 31
  D: 32
  E: 33
  F: 34
  G: 35
  H: 36
  I: 37
  J: 38
  K: 39
  L: 40
  M: 41
  N: 42
  O: 43
  P: 44
  Q: 45
  R: 46
  S: 47
  T: 48
  U: 49
  V: 50
  W: 51
  X: 52
  Y: 53
  Z: 54
  _0: 7
  _1: 8
  _2: 9
  _3: 10
  _4: 11
  _5: 12
  _6: 13
  _7: 14
  _8: 15
  _9: 16
